services:
  cpc_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV}
    command: npm run start:docker:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:${APP_INTERNAL_PORT}"
    depends_on:
      - cpc_mongo
    env_file:
      - .env
    networks:
      - canard

  cpc_mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - canard
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/coin --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks:
  canard: