services:
  cpc_webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./live/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./live/certbot/www:/var/www/certbot/:ro
      - ./live/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./live/certbot/www/:/var/www/certbot/:rw
      - ./live/certbot/conf/:/etc/letsencrypt/:rw