services:
  cpc_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV}
    command: npm run start:docker:dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./../canard-cafe-front/build:/app/front
    ports:
      - "${APP_PORT}:${APP_INTERNAL_PORT}"
    depends_on:
      - cpc_mongo
    env_file:
      - .env
    networks:
      - canard

  cpc_mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - canard
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongo localhost:${MONGO_PORT}/coin --quiet"
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./var/mongodb:/data/db

networks:
  canard: